// -----------------------------------------------------------------------
// <copyright file="VsRuleSetWriter.cs" company="Ollon, LLC">
//     Copyright (c) 2017 Ollon, LLC. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using System.ComponentModel.Composition;
using System.IO;
using System.Text;
using Ollon.VisualStudio.Extensibility.Services;

namespace Ollon.VisualStudio.Extensibility.Implementation.Services
{
    [Export(typeof(IVsRuleSetWriter))]
    internal class VsRuleSetWriter : IVsRuleSetWriter
    {
        public void WriteRuleSet(ISolutionOptions options)
        {
            string content = GenerateCodeAnalysisRuleSet(options.SolutionName);
            string ruleSetPath = Path.Combine(options.RuleSetDirectory, "SolutionRules.ruleset");
            FileInfo info = new FileInfo(ruleSetPath);
            if (!info.Directory.Exists)
            {
                info.Directory.Create();
            }
            File.WriteAllText(ruleSetPath, content);
        }

        private static string GenerateCodeAnalysisRuleSet(string solutionName)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine(@"<?xml version=""1.0"" encoding=""utf-8""?>");
            sb.AppendLine($@"<RuleSet Name=""{solutionName} Rules"" Description=""Solution-Level Code Analysis Rules for the {solutionName} solution."" ToolsVersion=""15.0"">");
            sb.AppendLine(@"  <Include Path=""extendedcorrectnessrules.ruleset"" Action=""Default"" />");
            sb.AppendLine(@"  <Include Path=""extendeddesignguidelinerules.ruleset"" Action=""Default"" />");
            sb.AppendLine(@"  <Rules AnalyzerId=""Microsoft.CodeAnalysis.CSharp"" RuleNamespace=""Microsoft.CodeAnalysis.CSharp"">");
            sb.AppendLine(@"    <Rule Id=""AD0001"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0078"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0105"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0108"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0109"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0114"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0162"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0164"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0168"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0183"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0184"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0197"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0219"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0251"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0252"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0253"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0278"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0279"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0280"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0282"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0419"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0420"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0435"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0436"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0437"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0440"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0458"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0464"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0465"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0469"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0472"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0473"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0612"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0618"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0626"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0628"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0642"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0652"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0657"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0658"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0659"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0660"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0661"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0665"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0672"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0675"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0684"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0693"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0728"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0809"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0811"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS0824"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1030"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1058"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1062"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1064"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1066"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1072"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1522"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1570"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1571"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1572"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1573"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1574"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1580"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1581"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1584"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1587"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1589"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1590"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1591"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1592"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1616"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1633"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1634"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1635"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1645"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1658"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1668"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1685"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1687"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1690"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1692"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1695"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1696"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1697"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1700"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1701"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1702"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1710"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1711"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1712"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1717"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1718"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1720"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1723"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1734"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1735"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1762"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1927"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1956"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1957"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1974"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1981"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS1998"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS2002"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS2008"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS2023"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS2029"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS2038"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3000"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3001"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3002"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3003"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3005"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3006"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3007"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3008"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3009"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3010"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3011"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3012"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3013"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3014"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3015"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3016"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3017"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3018"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3019"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3021"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3022"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3023"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3024"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3026"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS3027"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS4014"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS4024"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS4025"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS4026"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS7033"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS7035"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS7080"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS7081"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS7082"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS7090"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS7095"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8001"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8002"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8009"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8012"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8018"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8019"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8020"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8021"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8029"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8032"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8033"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8034"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8040"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8073"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8094"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8105"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""CS8123"" Action=""None"" />");
            sb.AppendLine("  </Rules>");
            sb.AppendLine(@"  <Rules AnalyzerId=""Microsoft.CodeAnalysis.CSharp.EditorFeatures"" RuleNamespace=""Microsoft.CodeAnalysis.CSharp.EditorFeatures"">");
            sb.AppendLine(@"    <Rule Id=""IDE0032"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0032WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine("  </Rules>");
            sb.AppendLine(@"  <Rules AnalyzerId=""Microsoft.CodeAnalysis.CSharp.Features"" RuleNamespace=""Microsoft.CodeAnalysis.CSharp.Features"">");
            sb.AppendLine(@"    <Rule Id=""IDE0001"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0002"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0003"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0004"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0005"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0007"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0007WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0008"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0008WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0009"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0009WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0011"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0011WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0012"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0013"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0014"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0015"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0016"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0016WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0017"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0017WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0018"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0018WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0019"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0019WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0020"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0020WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0021"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0021WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0022"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0022WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0023"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0023WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0024"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0024WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0025"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0025WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0026"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0026WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0027"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0027WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0028"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0028WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0029"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0029WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0030"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0030WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0031"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0031WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE1005"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE1005WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE1006"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE1006WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine("  </Rules>");
            sb.AppendLine(@"  <Rules AnalyzerId=""Microsoft.CodeAnalysis.Features"" RuleNamespace=""Microsoft.CodeAnalysis.Features"">");
            sb.AppendLine(@"    <Rule Id=""IDE0010"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0010WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0033"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""IDE0033WithoutSuggestion"" Action=""None"" />");
            sb.AppendLine("  </Rules>");
            sb.AppendLine(@"  <Rules AnalyzerId=""Roslynator.CSharp.Analyzers"" RuleNamespace=""Roslynator.CSharp.Analyzers"">");
            sb.AppendLine(@"    <Rule Id=""RCS1005FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1006FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1010"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1015FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1021FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1032FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1047FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1048FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1049FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1058FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1061FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1071"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1089FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1091FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1110"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1112FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1114FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1124FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1127FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1166"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1174FadeOut"" Action=""None"" />");
            sb.AppendLine(@"    <Rule Id=""RCS1182"" Action=""None"" />");
            sb.AppendLine("  </Rules>");
            sb.AppendLine("</RuleSet>");
            return sb.ToString();
        }
    }
}
